### ISSUE TITLE
can you add abnormal of event item?

### ISSUE THREAD

**Issue by siambr** [Tera-Shiraneko/monitor-control#1]
there is an event item id 206770 on sea server which is cause drunk screen atm.

**Comment by Tera-Shiraneko** [comment]
I need the abnormality id of it after item usage since I have no sea client.

**Comment by Tera-Shiraneko** [comment]
Or just upload me the datacenter of the client should be located in S1Data.

**Comment by Tera-Shiraneko** [comment]
Ok I added the abnormality id of the new item can you please tell me if its working since I cant test it cause the other regions doesn't have the patch atm.

**Comment by siambr** [comment]
sadly it's still cause dizzy screen.
I think it's the same effect when black dragon (at apex quest) almost killed you.

**Comment by Tera-Shiraneko** [comment]
Can you try with deleting old module and downloading new one.

**Comment by siambr** [comment]
after I did clean install. it's work now like a charm . Thank you !!

**Comment by Tera-Shiraneko** [comment]
Glad to hear that it's working now.
