### ISSUE TITLE
hook: Error: obsolete definition (S_ABNORMALITY_BEGIN.3)

### ISSUE THREAD

**Issue by FrankMora** [Tera-Shiraneko/monitor-control#2]
hook: Error: obsolete definition (S_ABNORMALITY_BEGIN.3)

**Comment by Tera-Shiraneko** [comment]
Will fix it soon. But it's better if you use fps-manager. As it's way better functionality wise.

**Comment by Tera-Shiraneko** [comment]
Issue has been fixed @FrankMora
